'use strict';
const traits=['logic','courage','kindness','energy','mystery','leadership','creativity','calm'];
const characters={
 conan:{name:'江戸川コナン',reading:'えどがわ コナン',icon:'🎀',tagline:'冷静な名探偵タイプ',desc:'小さな手がかりも見逃さず、落ち着いて答えへ近づくタイプ。困っている人を守るために、知恵と勇気を使えます。',compat:'ran',compatText:'あなたの冷静さと、蘭のやさしさ・行動力が互いを支えます。',v:{logic:5,courage:4,kindness:3,energy:3,mystery:3,leadership:4,creativity:3,calm:5}},
 haibara:{name:'灰原哀',reading:'はいばら あい',icon:'🧪',tagline:'クールな知性派タイプ',desc:'よく観察し、感情に流されずに考えられるタイプ。言葉は少なくても、大切な人を静かに気づかいます。',compat:'conan',compatText:'互いの知性を尊重しながら、難しい問題にも協力して向き合えます。',v:{logic:5,courage:3,kindness:3,energy:1,mystery:5,leadership:2,creativity:4,calm:5}},
 ran:{name:'毛利蘭',reading:'もうり らん',icon:'🥋',tagline:'強くてやさしい守り手タイプ',desc:'まっすぐで思いやりがあり、いざという時には大切な人を守れるタイプ。周りに安心感を与えます。',compat:'conan',compatText:'あなたのあたたかさがコナンの冷静さを支え、最高のチームになります。',v:{logic:2,courage:5,kindness:5,energy:4,mystery:1,leadership:3,creativity:2,calm:3}},
 kid:{name:'怪盗キッド',reading:'かいとう キッド',icon:'🎩',tagline:'華麗なエンターテイナータイプ',desc:'ひらめきと大胆さで、みんなを驚かせるタイプ。ピンチでもユーモアを忘れず、鮮やかに切り抜けます。',compat:'conan',compatText:'競い合うほど互いの力が引き出される、好敵手のような相性です。',v:{logic:4,courage:4,kindness:2,energy:4,mystery:5,leadership:3,creativity:5,calm:4}},
 kazuha:{name:'遠山和葉',reading:'とおやま かずは',icon:'🍀',tagline:'明るく一途な応援タイプ',desc:'素直で元気、仲間を心から応援できるタイプ。感情豊かで、困った時には迷わず力を貸します。',compat:'heiji',compatText:'あなたの素直さが平次の行動力を支え、息の合ったパートナーになれます。',v:{logic:2,courage:4,kindness:5,energy:5,mystery:1,leadership:2,creativity:2,calm:2}},
 heiji:{name:'服部平治',reading:'はっとり へいじ',icon:'🧢',tagline:'熱血・行動派探偵タイプ',desc:'正義感が強く、考えたらすぐに動けるタイプ。仲間思いで、難しい勝負ほど燃えます。',compat:'kazuha',compatText:'あなたの行動力を和葉の思いやりが支え、自然体で助け合えます。',v:{logic:5,courage:5,kindness:3,energy:5,mystery:2,leadership:4,creativity:2,calm:2}},
 kogoro:{name:'毛利小五郎',reading:'もうり こごろう',icon:'👔',tagline:'愛されムードメーカータイプ',desc:'人間味があり、場を明るくするタイプ。ここぞという時には家族や仲間への強い思いを見せます。',compat:'megure',compatText:'目暮警部の堅実さとあなたの勢いが合わさると、頼れるコンビになります。',v:{logic:2,courage:3,kindness:3,energy:5,mystery:1,leadership:3,creativity:2,calm:1}},
 chihaya:{name:'萩原千速',reading:'はぎわら ちはや',icon:'🏍️',tagline:'颯爽としたヒーロータイプ',desc:'迷いのない行動と強い責任感を持つタイプ。困っている人を見れば、すぐに手を差し伸べられます。',compat:'jugo',compatText:'横溝重悟の真面目さと、あなたの大胆な行動力がよくかみ合います。',v:{logic:3,courage:5,kindness:4,energy:4,mystery:3,leadership:5,creativity:2,calm:4}},
 jugo:{name:'横溝重悟',reading:'よこみぞ じゅうご',icon:'🚔',tagline:'実直な正義派タイプ',desc:'ルールと責任を大切にし、最後までやり抜くタイプ。少し不器用でも、信頼される誠実さがあります。',compat:'chihaya',compatText:'萩原千速のしなやかな行動力が、あなたの実直さを前へ進めます。',v:{logic:3,courage:4,kindness:2,energy:3,mystery:1,leadership:5,creativity:1,calm:3}},
 amuro:{name:'降谷零（安室透）',reading:'ふるや れい（あむろ とおる）',icon:'☕',tagline:'万能なプロフェッショナルタイプ',desc:'観察力、行動力、気配りをバランスよく備えたタイプ。状況に合わせて役割を変え、任務をやり遂げます。',compat:'conan',compatText:'コナンの推理力とあなたの総合力で、難題にも多方面から挑めます。',v:{logic:5,courage:5,kindness:3,energy:4,mystery:5,leadership:5,creativity:4,calm:5}},
 megure:{name:'目暮警部',reading:'めぐれ けいぶ',icon:'🎩',tagline:'みんなをまとめる安定タイプ',desc:'正義感と責任感があり、チームを落ち着いてまとめるタイプ。経験を生かし、周りを信頼して任せられます。',compat:'kogoro',compatText:'小五郎の思い切りのよさを、あなたの安定感がうまく受け止めます。',v:{logic:3,courage:3,kindness:4,energy:2,mystery:1,leadership:5,creativity:1,calm:4}},
 mitsuhiko:{name:'円谷光彦',reading:'つぶらや みつひこ',icon:'📚',tagline:'まじめな研究家タイプ',desc:'知りたいことを自分で調べ、丁寧に考えるタイプ。礼儀正しく、仲間のために知識を役立てます。',compat:'ayumi',compatText:'歩美の明るさがあなたの知識を引き出し、楽しく協力できます。',v:{logic:4,courage:2,kindness:4,energy:2,mystery:1,leadership:2,creativity:3,calm:4}},
 ayumi:{name:'吉田歩美',reading:'よしだ あゆみ',icon:'🌸',tagline:'やさしいポジティブタイプ',desc:'素直で明るく、人のよいところを見つけられるタイプ。あなたのひと声が、仲間に勇気を与えます。',compat:'mitsuhiko',compatText:'光彦の慎重さとあなたの明るさで、安心して助け合える相性です。',v:{logic:2,courage:3,kindness:5,energy:4,mystery:1,leadership:2,creativity:3,calm:2}},
 genta:{name:'小嶋元太',reading:'こじま げんた',icon:'🍚',tagline:'元気いっぱいの突撃タイプ',desc:'細かいことより、まずやってみるタイプ。仲間への気持ちが熱く、チームに元気と勢いを与えます。',compat:'agasa',compatText:'阿笠博士の知恵があなたのパワーを支え、楽しい挑戦ができます。',v:{logic:1,courage:4,kindness:3,energy:5,mystery:1,leadership:3,creativity:1,calm:1}},
 agasa:{name:'阿笠博士',reading:'あがさ はかせ',icon:'⚙️',tagline:'ひらめき発明家タイプ',desc:'好奇心が強く、失敗しても工夫を重ねられるタイプ。知恵とユーモアで、仲間を後ろから支えます。',compat:'genta',compatText:'元太の元気とあなたの発想力が合わさり、思わぬアイデアが生まれます。',v:{logic:4,courage:2,kindness:5,energy:3,mystery:2,leadership:2,creativity:5,calm:3}}
};
const questions=[
 {icon:'🏫',q:'<ruby>放課後<rt>ほうかご</rt></ruby>、いちばんやってみたいことは？',a:[['<ruby>図書館<rt>としょかん</rt></ruby>で<ruby>気<rt>き</rt></ruby>になることを<ruby>調<rt>しら</rt></ruby>べる',{logic:3,calm:2}],['<ruby>友達<rt>ともだち</rt></ruby>とスポーツをする',{energy:3,courage:2}],['みんなの<ruby>相談<rt>そうだん</rt></ruby>にのる',{kindness:3,leadership:1}],['<ruby>工作<rt>こうさく</rt></ruby>やマジックを<ruby>考<rt>かんが</rt></ruby>える',{creativity:3,mystery:2}]]},
 {icon:'🧩',q:'<ruby>難<rt>むずか</rt></ruby>しいなぞを<ruby>見<rt>み</rt></ruby>つけたら？',a:[['<ruby>手<rt>て</rt></ruby>がかりを<ruby>順番<rt>じゅんばん</rt></ruby>に<ruby>整理<rt>せいり</rt></ruby>する',{logic:4,calm:2}],['とにかく<ruby>現場<rt>げんば</rt></ruby>へ<ruby>行<rt>い</rt></ruby>ってみる',{courage:3,energy:2}],['みんなで<ruby>話<rt>はな</rt></ruby>し<ruby>合<rt>あ</rt></ruby>う',{kindness:2,leadership:2}],['だれも<ruby>思<rt>おも</rt></ruby>いつかない<ruby>方法<rt>ほうほう</rt></ruby>を<ruby>試<rt>ため</rt></ruby>す',{creativity:4,mystery:1}]]},
 {icon:'🌧️',q:'<ruby>友達<rt>ともだち</rt></ruby>が<ruby>落<rt>お</rt></ruby>ち<ruby>込<rt>こ</rt></ruby>んでいたら？',a:[['<ruby>原因<rt>げんいん</rt></ruby>を<ruby>一緒<rt>いっしょ</rt></ruby>に<ruby>考<rt>かんが</rt></ruby>える',{logic:2,kindness:2}],['すぐに<ruby>会<rt>あ</rt></ruby>いに<ruby>行<rt>い</rt></ruby>く',{courage:2,energy:2,kindness:2}],['そばにいて、やさしく<ruby>話<rt>はなし</rt></ruby>を<ruby>聞<rt>き</rt></ruby>く',{kindness:4,calm:2}],['<ruby>笑<rt>わら</rt></ruby>えることをして<ruby>元気<rt>げんき</rt></ruby>づける',{creativity:2,energy:3}]]},
 {icon:'🎤',q:'みんなの<ruby>前<rt>まえ</rt></ruby>で<ruby>発表<rt>はっぴょう</rt></ruby>するなら？',a:[['データをそろえて<ruby>論理的<rt>ろんりてき</rt></ruby>に<ruby>話<rt>はな</rt></ruby>す',{logic:3,calm:2}],['<ruby>元気<rt>げんき</rt></ruby>よく<ruby>堂々<rt>どうどう</rt></ruby>と<ruby>話<rt>はな</rt></ruby>す',{courage:3,energy:3}],['<ruby>聞<rt>き</rt></ruby>く<ruby>人<rt>ひと</rt></ruby>の<ruby>気持<rt>きも</rt></ruby>ちを<ruby>考<rt>かんが</rt></ruby>える',{kindness:3,leadership:2}],['<ruby>楽<rt>たの</rt></ruby>しい<ruby>演出<rt>えんしゅつ</rt></ruby>で<ruby>驚<rt>おどろ</rt></ruby>かせる',{creativity:3,mystery:3}]]},
 {icon:'🚪',q:'<ruby>急<rt>きゅう</rt></ruby>なトラブルが<ruby>起<rt>お</rt></ruby>きた！どうする？',a:[['まず<ruby>状況<rt>じょうきょう</rt></ruby>をよく<ruby>確認<rt>かくにん</rt></ruby>する',{logic:3,calm:3}],['<ruby>自分<rt>じぶん</rt></ruby>が<ruby>先頭<rt>せんとう</rt></ruby>に<ruby>立<rt>た</rt></ruby>つ',{courage:3,leadership:3}],['<ruby>困<rt>こま</rt></ruby>っている<ruby>人<rt>ひと</rt></ruby>を<ruby>優先<rt>ゆうせん</rt></ruby>する',{kindness:4,courage:1}],['その<ruby>場<rt>ば</rt></ruby>にあるもので<ruby>解決策<rt>かいけつさく</rt></ruby>を<ruby>作<rt>つく</rt></ruby>る',{creativity:4,energy:1}]]},
 {icon:'🎁',q:'プレゼントを<ruby>選<rt>えら</rt></ruby>ぶときに<ruby>大切<rt>たいせつ</rt></ruby>なのは？',a:[['<ruby>相手<rt>あいて</rt></ruby>の<ruby>好<rt>す</rt></ruby>きをしっかり<ruby>調<rt>しら</rt></ruby>べる',{logic:2,calm:2}],['<ruby>思<rt>おも</rt></ruby>い<ruby>切<rt>き</rt></ruby>って<ruby>特別<rt>とくべつ</rt></ruby>なものを<ruby>選<rt>えら</rt></ruby>ぶ',{courage:2,mystery:2}],['<ruby>気持<rt>きも</rt></ruby>ちが<ruby>伝<rt>つた</rt></ruby>わること',{kindness:4}],['<ruby>手作<rt>てづく</rt></ruby>りやサプライズ',{creativity:4,energy:1}]]},
 {icon:'🗺️',q:'<ruby>知<rt>し</rt></ruby>らない<ruby>場所<rt>ばしょ</rt></ruby>で<ruby>道<rt>みち</rt></ruby>に<ruby>迷<rt>まよ</rt></ruby>ったら？',a:[['<ruby>地図<rt>ちず</rt></ruby>と<ruby>目印<rt>めじるし</rt></ruby>を<ruby>確認<rt>かくにん</rt></ruby>する',{logic:3,calm:2}],['<ruby>気<rt>き</rt></ruby>になる<ruby>方向<rt>ほうこう</rt></ruby>へ<ruby>進<rt>すす</rt></ruby>む',{courage:2,energy:3}],['<ruby>近<rt>ちか</rt></ruby>くの<ruby>人<rt>ひと</rt></ruby>に<ruby>聞<rt>き</rt></ruby>く',{kindness:2,leadership:1}],['<ruby>高<rt>たか</rt></ruby>い<ruby>場所<rt>ばしょ</rt></ruby>や<ruby>別<rt>べつ</rt></ruby>の<ruby>道<rt>みち</rt></ruby>を<ruby>探<rt>さが</rt></ruby>す',{creativity:3,mystery:2}]]},
 {icon:'👥',q:'チームでのあなたの<ruby>役割<rt>やくわり</rt></ruby>は？',a:[['<ruby>作戦<rt>さくせん</rt></ruby>を<ruby>考<rt>かんが</rt></ruby>える',{logic:3,calm:2}],['みんなを<ruby>引<rt>ひ</rt></ruby>っぱる',{courage:2,leadership:4}],['<ruby>仲間<rt>なかま</rt></ruby>を<ruby>支<rt>ささ</rt></ruby>える',{kindness:4,calm:1}],['<ruby>新<rt>あたら</rt></ruby>しいアイデアを<ruby>出<rt>だ</rt></ruby>す',{creativity:4,energy:1}]]},
 {icon:'🌟',q:'<ruby>自分<rt>じぶん</rt></ruby>の<ruby>長所<rt>ちょうしょ</rt></ruby>に<ruby>近<rt>ちか</rt></ruby>いのは？',a:[['よく<ruby>考<rt>かんが</rt></ruby>えてから<ruby>動<rt>うご</rt></ruby>ける',{logic:3,calm:3}],['こわくても<ruby>挑戦<rt>ちょうせん</rt></ruby>できる',{courage:4,energy:1}],['<ruby>人<rt>ひと</rt></ruby>の<ruby>気持<rt>きも</rt></ruby>ちに<ruby>気<rt>き</rt></ruby>づける',{kindness:4}],['<ruby>面白<rt>おもしろ</rt></ruby>いことを<ruby>思<rt>おも</rt></ruby>いつける',{creativity:4,mystery:1}]]},
 {icon:'🏁',q:'<ruby>大<rt>おお</rt></ruby>きな<ruby>目標<rt>もくひょう</rt></ruby>に<ruby>挑戦<rt>ちょうせん</rt></ruby>するときは？',a:[['<ruby>計画<rt>けいかく</rt></ruby>を<ruby>立<rt>た</rt></ruby>てて<ruby>一歩<rt>いっぽ</rt></ruby>ずつ<ruby>進<rt>すす</rt></ruby>む',{logic:3,calm:3}],['<ruby>失敗<rt>しっぱい</rt></ruby>を<ruby>恐<rt>おそ</rt></ruby>れず<ruby>飛<rt>と</rt></ruby>び<ruby>込<rt>こ</rt></ruby>む',{courage:4,energy:2}],['<ruby>仲間<rt>なかま</rt></ruby>と<ruby>励<rt>はげ</rt></ruby>まし<ruby>合<rt>あ</rt></ruby>う',{kindness:3,leadership:2}],['<ruby>自分<rt>じぶん</rt></ruby>だけのやり<ruby>方<rt>かた</rt></ruby>で<ruby>目指<rt>めざ</rt></ruby>す',{creativity:3,mystery:3}]]}
];
let current=0,answers=[],score=Object.fromEntries(traits.map(t=>[t,0]));
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function resetScore(){score=Object.fromEntries(traits.map(t=>[t,0]));answers.forEach((choice,i)=>{if(choice!=null) apply(questions[i].a[choice][1],1);});}
function apply(points,mult){Object.entries(points).forEach(([k,v])=>score[k]+=v*mult);}
function renderQuestion(){const q=questions[current];$('question-counter').textContent=`${current+1} / ${questions.length}`;$('progress-bar').style.width=`${((current+1)/questions.length)*100}%`;$('question-icon').textContent=q.icon;$('question-text').innerHTML=q.q;$('back-button').style.visibility=current===0?'hidden':'visible';$('answer-list').innerHTML='';q.a.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.className='answer-button';b.innerHTML=`${String.fromCharCode(65+i)}. ${item[0]}`;b.onclick=()=>choose(i);$('answer-list').appendChild(b);});}
function choose(i){answers[current]=i;resetScore();if(current<questions.length-1){current++;renderQuestion();}else runThinking();}
function runThinking(){show('thinking-screen');$('thinking-title').innerHTML='<ruby>推理中<rt>すいりちゅう</rt></ruby>...';$('thinking-message').innerHTML='<ruby>回答<rt>かいとう</rt></ruby>を<ruby>調<rt>しら</rt></ruby>べています';setTimeout(()=>{$('thinking-title').innerHTML='<ruby>結果<rt>けっか</rt></ruby>がわかった！';$('thinking-message').innerHTML='<ruby>君<rt>きみ</rt></ruby>に<ruby>近<rt>ちか</rt></ruby>いキャラクターは...';},1200);setTimeout(renderResult,2500);}
function ranked(){return Object.entries(characters).map(([id,c])=>{let distance=0,max=0;traits.forEach(t=>{distance+=Math.abs(score[t]-c.v[t]*6);max+=30;});return{id,...c,raw:Math.max(0,100-distance/max*100)};}).sort((a,b)=>b.raw-a.raw);}
function renderResult(){const list=ranked(),top=list[0],compat=characters[top.compat];$('result-icon').textContent=top.icon;$('result-name').innerHTML=`<ruby>${top.name}<rt>${top.reading}</rt></ruby>タイプ！`;$('result-tagline').textContent=top.tagline;$('result-description').textContent=top.desc;$('compatibility-icon').textContent=compat.icon;$('compatibility-name').innerHTML=`<ruby>${compat.name}<rt>${compat.reading}</rt></ruby>`;$('compatibility-text').textContent=top.compatText;$('ranking-list').innerHTML='';const topRaw=list[0].raw;list.slice(0,3).forEach((c,i)=>{const pct=Math.max(65,Math.round(96-(topRaw-c.raw)*2-i*4));const row=document.createElement('div');row.className='ranking-row';row.innerHTML=`<div class="ranking-label"><span>${['🥇','🥈','🥉'][i]} ${c.icon} ${c.name}</span><span>${pct}%</span></div><div class="ranking-track"><div class="ranking-fill" style="width:${pct}%"></div></div>`;$('ranking-list').appendChild(row);});const text=`私は「${top.name}タイプ」でした！ ${top.tagline} #名探偵コナン診断ゲーム`;const page=location.href.split('#')[0];$('share-x').href=`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(page)}`;$('share-line').href=`https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(page)}&text=${encodeURIComponent(text)}`;$('copy-result').onclick=()=>copyText(`${text}\n${page}`);show('result-screen');}
async function copyText(text){try{await navigator.clipboard.writeText(text);$('copy-status').textContent='結果をコピーしました！';}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();$('copy-status').textContent='結果をコピーしました！';}}
$('start-button').onclick=()=>{current=0;answers=[];resetScore();renderQuestion();show('quiz-screen');};$('back-button').onclick=()=>{if(current>0){current--;answers=answers.slice(0,current+1);resetScore();renderQuestion();}};$('restart-button').onclick=()=>{current=0;answers=[];resetScore();$('copy-status').textContent='';show('start-screen');};
